//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraLuggage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        [Display(Name = "Số thứ tự")]
        public int orderdetail_id { get; set; }

        [Display(Name = "Mã sản phẩm")]
        public string od_product { get; set; }

        [Display(Name = "Số lượng mua")]
        public Nullable<int> od_quantity { get; set; }

        [Display(Name = "Giá")]
        public Nullable<double> od_price { get; set; }

        [Display(Name = "Số thứ tự hóa đơn")]
        public Nullable<int> od_orderno { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
