//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraLuggage.Models
{
    using CaraLuggage.Controllers.StatePattern;
    using CaraLuggage.Controllers.Visitor;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHang : IDonHang
    {
        private OrderState currentState;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            currentState = new NotConfirmState(); 
        }

        public void changeState(OrderState state)
        {
            currentState = state;
        }

        public void ProcessOrder(DonHang donHang)
        {
            currentState.ProcessOrder(donHang);
        }

        [Display(Name = "Số thứ tự")]
        public int order_no { get; set; }

        [Display(Name = "Mã đơn hàng")]
        public string order_code { get; set; }

        [Display(Name = "Ngày tạo đơn")]
        public Nullable<System.DateTime> order_createAt { get; set; }

        [Display(Name = "Khách hàng")]
        public string order_customer { get; set; }

        [Display(Name = "Nhân viên")]
        public string order_staff { get; set; }

        [Display(Name = "Tình trạng đơn")]
        public string order_status { get; set; }

        [Display(Name = "Phương thức thanh toán")]
        public Nullable<int> order_payment { get; set; }

        [Display(Name = "Tổng tiền")]
        public Nullable<double> order_totalPrice { get; set; }

        [Display(Name = "Ngày chỉnh sửa đơn")]
        public Nullable<System.DateTime> order_modifiedAt { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        public virtual NhanVien NhanVien { get; set; }

        public void Accept()
        {

        }
    }
}
