//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraLuggage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }

        [Display(Name = "ID Sản phẩm")]
        public string product_id { get; set; }

        [Display(Name = "Tên SP")]
        public string product_name { get; set; }

        [Display(Name = "Màu sắc")]
        public Nullable<int> product_color { get; set; }

        [Display(Name = "Xuất xứ")]
        public string product_origin { get; set; }

        [Display(Name = "Kích thước")]
        public string product_size { get; set; }

        [Display(Name = "Giá")]
        public Nullable<double> product_price { get; set; }

        [Display(Name = "Hình ảnh")]
        public string product_image { get; set; }

        [Display(Name = "Chất liệu")]
        public Nullable<int> product_material { get; set; }

        [Display(Name = "Số lượng")]
        public int product_quantity { get; set; }

        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> product_createAt { get; set; }

        [Display(Name = "Trạng thái")]
        public Nullable<bool> product_status { get; set; }

        [Display(Name = "Danh mục")]
        public Nullable<int> product_category { get; set; }

        [Display(Name = "Thương hiệu")]
        public Nullable<int> product_brand { get; set; }

        public virtual ChatLieu ChatLieu { get; set; }

        [Display(Name = "Chi tiết đơn hàng")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }

        public virtual MauSac MauSac { get; set; }

        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
